[package]
name = "basic-actix-askama-multilingual-page"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.19"
askama = "0.11.0"
tokio = "1"
